    public class LUMANTAO_ACTIVITY_1 {
        public static void main(String[args]){
        int a = 25;
        int b = 50;
        int c = 75;
    
        int d = a+b;
        int e = a-c;
        int f = b*c;
    
        System.out.println("Sum = " + d);
        System.out.println("Difference = " + c);
        System.out.println("Product = " + f);
    
    
    
    }    
    }



    